# Generated by Django 4.1.5 on 2023-01-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
